<a href="https://colab.research.google.com/github/HabibParvej/DataAnalysis_MCA/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello")

Hello


In [ ]:
import numpy as np

In [ ]:
list_data=[1,2,3,4,5]
array_from_list = np.array(list_data)  # Convert List To Array
print("Array from list:",array_from_list)

Array from list: [1 2 3 4 5]


In [ ]:
# Creating 1D Array
array_1d = np.array([10,20,30])
print("1D Array",array_1d)

1D Array [10 20 30]


In [ ]:
# Creating 2D Array(matrix like)
array_2D = ([[1,2,3],[4,5,6]])  #2 rows 3 columns
print("2D Array:\n",array_2D)


2D Array:
 [[1, 2, 3], [4, 5, 6]]


In [ ]:
# Creating evenly spaced integers with arange (like python range)
array_range = np.arange(0,10,2) # from 0 to 8 with step size of 2
print("Range Array:",array_range)

Range Array: [0 2 4 6 8]


In [ ]:
# Create evenly spaced floats using linespace
array_linspace = np.linspace(0,1,5) #5 values from 0 to 1
print("Linspace array",array_linspace)

Linspace array [0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Create 2 x 3 array of all zeroes
zeros_array = np.zeros((2,3))
print("Zeros Array",zeros_array)

Zeros Array [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Create 3x2 Array of all ones
ones_array = np.ones((3,2))
print("Array Of Ones:",ones_array)

Array Of Ones: [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Create a 2x2 array filled with value 7
full_array = np.full((2,2),7)
print("Full Array\n",full_array)

Full Array
 [[7 7]
 [7 7]]


In [ ]:
# Define a 2D array
sample_array = np.array([[1,2,3],[4,5,6]])
print("Sample Array:",sample_array)

# Shape:  tuple of rows (rows,columns)
print("Shape:",sample_array.shape)

#ndim: number of dimensions (axes.1D,2D,3D)
print("Number of Dimession",sample_array.ndim)

#dtype:
print("DataType:",sample_array.dtype)

#size:
print("Total Elements:",sample_array.size)



Sample Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimession 2
DataType: int64
Total Elements: 6


In [ ]:
# Each row represents a product, each column represents sales in months Jan to Mar
sales_data = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

print("Data", sales_data)


Data [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Element at row 0, column 1 (Product A in Feb)
print("Element at [0,1]:", sales_data[0, 1])

# Entire first row (Product A)
print("First row:", sales_data[0])

# Last column (March for all products)
print("Last column:", sales_data[:, -1])

# Subarray: First 2 rows and first 2 columns
print("Block (first 2 rows, first 2 columns):\n", sales_data[:2, :2])

# Reverse the order of rows (Products C, B, A)
print("Reversed Rows:\n", sales_data[::-1])

# Every other column (Jan and Mar)
print("Every other column:\n", sales_data[:, ::-1])

Element at [0,1]: 2
First row: [1 2 3]
Last column: [3 6 9]
Block (first 2 rows, first 2 columns):
 [[1 2]
 [4 5]]
Reversed Rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Every other column:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
print("Every other column:\n", sales_data[-1: -3: -1])

Every other column:
 [[7 8 9]
 [4 5 6]]


In [ ]:
print("Every other column:\n", sales_data[-1: -3])

Every other column:
 []


In [ ]:
print("Last Row:\n", sales_data[-1])

Last Row:
 [7 8 9]


In [ ]:
print("2nd last row:\n", sales_data[-2])

2nd last row:
 [4 5 6]


In [ ]:
Time_series = np.array([[1, 2, 3,4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12]])

print("Data:\n", Time_series)

Data:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# First Column
print("2nd last row:\n", Time_series[:,0])

2nd last row:
 [1 5 9]


In [ ]:
# Last Two Columns
print("2nd last row:\n", Time_series[:,2:])

2nd last row:
 [[ 3  4]
 [ 7  8]
 [11 12]]


In [ ]:
# Time Series
time_series = np.arange(1, 13).reshape(3, 4)
print("Time Series Data:\n", time_series)


Time Series Data:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Numerical And Conditional & Coditional Logic

# Define two simple arrays of the same shape
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

# Perform basic arithmetic operations
print("Addition:", arr1 + arr2)           # [11 22 33 44]
print("Subtraction:", arr1 - arr2)        # [ 9 18 27 36]
print("Multiplication:", arr1 * arr2)     # [ 10  40  90 160]
print("Division:", arr1 / arr2)           # [10. 10. 10. 10.]

# Array and scalar operation
print("Add 100 to arr1:", arr1 + 100)     # [110 120 130 140]

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Add 100 to arr1: [110 120 130 140]


In [ ]:
# 2D_array example
matrix = np.array([
    [5, 10, 15],
    [20, 25, 30]
])

# Full-array aggregations
print("Total Sum:", np.sum(matrix))
print("Mean Value:", np.mean(matrix))
print("Standard Deviation:", np.std(matrix))

# Axis-wise aggregations
print("Sum by column (axis=0):", np.sum(matrix, axis=0))
print("Sum by row (axis=1):", np.sum(matrix, axis=1))
print("Mean by row (axis=1):", np.mean(matrix, axis=1))

Total Sum: 105
Mean Value: 17.5
Standard Deviation: 8.539125638299666
Sum by column (axis=0): [25 35 45]
Sum by row (axis=1): [30 75]
Mean by row (axis=1): [10. 25.]


In [ ]:
scores = np.array([60, 75, 85, 90, 45])

# Create a boolean mask for scores >= 70
pass_mask = scores >= 70
print("Pass mask:", pass_mask)

# Filter values using the mask
print("Passing scores:", scores[pass_mask])

# Combine conditions: select scores between 70 and 90 (inclusive)
print("Scores between 70 and 90:", scores[(scores >= 70) & (scores <= 90)])

Pass mask: [False  True  True  True False]
Passing scores: [75 85 90]
Scores between 70 and 90: [75 85 90]


In [ ]:
# Use np.where to assign labels
labels = np.where(scores >= 70, "Pass", "Fail")
print("Labels for scores:", labels)

Labels for scores: ['Fail' 'Pass' 'Pass' 'Pass' 'Fail']


In [ ]:
# Create an array with NaN values
data_with_nan = np.array([3.0, np.nan, 7.0, np.nan, 5.0])

# Detect NaN positions
print("NaN mask:", np.isnan(data_with_nan))

# Aggregate safely while ignoring NaNs
print("Mean ignoring NaNs:", np.nanmean(data_with_nan))

# Replace NaNs with 0
filled_data = np.nan_to_num(data_with_nan, nan=5.0)
print("Replaced NaNs with 0:", filled_data)

NaN mask: [False  True False  True False]
Mean ignoring NaNs: 5.0
Replaced NaNs with 0: [3. 5. 7. 5. 5.]


In [ ]:
# Create a 1D array of 12 elements
arr = np.arange(12)
print("Original array:", arr)

# Reshape into 3x4 (3 rows, 4 columns)
reshaped = arr.reshape(3, 4)
print("Reshaped (3x4):\n", reshaped)

# Flatten using ravel (view) and flatten (copy)
raveled = reshaped.ravel()
flattened = reshaped.flatten()

print("Raveled (1D view):", raveled)
print("Flattened (1D copy):", flattened)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Raveled (1D view): [ 0  1  2  3  4  5  6  7  8  9 10 11]
Flattened (1D copy): [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
print(id(raveled),id(flattened))

134601734110448 134601734108720


In [ ]:
transpose = matrix.T
print("Transpose MAtrix is :",transpose)

Transpose MAtrix is : [[ 5 20]
 [10 25]
 [15 30]]


In [ ]:
temps_transposed = matrix.T
print("\nTransposed (rows = times of day, cols = months):\n", temps_transposed)

# Convert one row  to a column
row = matrix[0]
col = matrix.reshape(-1, 1)
print("\row to col :\n", col)

# Convert back to row
month1_row_again = matrix.reshape(1, -1)
print("\nrow again:\n", month1_row_again)


Transposed (rows = times of day, cols = months):
 [[ 5 20]
 [10 25]
 [15 30]]
ow to col :
 [[ 5]
 [10]
 [15]
 [20]
 [25]
 [30]]

row again:
 [[ 5 10 15 20 25 30]]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Horizontal stack (along columns)
h_stack = np.hstack((a, b))
print("Horizontal Stack:\n", h_stack)

# Vertical stack (along rows)
v_stack = np.vstack((a, b))
print("Vertical Stack:\n", v_stack)

# Generic concatenate: axis=0 (rows), axis=1 (columns)
concat_axis0 = np.concatenate((a, b), axis=0)
concat_axis1 = np.concatenate((a, b), axis=1)
print("Concatenate axis=0:\n", concat_axis0)
print("Concatenate axis=1:\n", concat_axis1)

Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Create a 2D array
arr = np.arange(16).reshape(4, 4)
print("Original Array:\n", arr)

# Split vertically into two 2x4 arrays
split_vert = np.vsplit(arr, 2)
print("Vertical Split (2x4 each):")
for s in split_vert:
    print(s)

# Split horizontally into two 4x2 arrays
split_horiz = np.hsplit(arr, 2)
print("Horizontal Split (4x2 each):")
for s in split_horiz:
    print(s)

Original Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Vertical Split (2x4 each):
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
Horizontal Split (4x2 each):
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [ ]:
arr = np.array([
    [100, 101, 102],
    [110, 111, 112],
    [120, 121, 122],
    [130, 131, 132]
])

# Select rows 0, 2 and 3
selected_rows = arr[[0, 2, 3]]
print("Selected rows 0, 2, 3:\n", selected_rows)

# Reorder columns
reordered_cols = arr[:, [2, 0, 1]]
print("Reordered columns (2, 0, 1):\n", reordered_cols)

Selected rows 0, 2, 3:
 [[100 101 102]
 [120 121 122]
 [130 131 132]]
Reordered columns (2, 0, 1):
 [[102 100 101]
 [112 110 111]
 [122 120 121]
 [132 130 131]]


In [ ]:
data = np.array([45, 12, 89, 33])

# Sorted values
sorted_data = np.sort(data)
print("Sorted Data:", sorted_data)

# Indices that would sort the array
sort_order = np.argsort(data)
print("Sort Order Indices:", sort_order)

# Use sort_order to reorder the array manually
print("Data sorted using indices:", data[sort_order])

Sorted Data: [12 33 45 89]
Sort Order Indices: [1 3 0 2]
Data sorted using indices: [12 33 45 89]


In [1]:
import numpy as np

# Simulated sales data (rows = products, columns = months)
sales = np.array([
    [200, 220, 250, 300], # Product A
    [150, 160, 170, 190], # Product B
    [300, 330, 360, 390]  # Product C
])

# Row-wise sum (total sales per product)
row_sum = np.sum(sales, axis=1)
print("Total sales per product:", row_sum)

# Column-wise mean (average sales in each month)
col_mean = np.mean(sales, axis=0)
print("Average monthly sales:", col_mean)
# Percent change across months
# (current - previous) / previous
pct_change = (sales[:, 1:] - sales[:, :-1]) / sales[:, :-1]
print("Percent change:\n", pct_change)

Total sales per product: [ 970  670 1380]
Average monthly sales: [216.66666667 236.66666667 260.         293.33333333]
Percent change:
 [[0.1        0.13636364 0.2       ]
 [0.06666667 0.0625     0.11764706]
 [0.1        0.09090909 0.08333333]]


In [2]:
print(sales[:, :-1])

[[200 220 250]
 [150 160 170]
 [300 330 360]]


In [3]:
print(sales[:, 1:])

[[220 250 300]
 [160 170 190]
 [330 360 390]]


In [4]:
# Set seed for reproducibility
np.random.seed(42)

# Random integers
random_ints = np.random.randint(1, 100, size=(3, 4))
print("Random integers:\n", random_ints)

# Normally distributed values (mean=0, std=1)
normal_samples = np.random.normal(loc=0, scale=1, size=5)
print("Normal samples:", normal_samples)

# Random choice from list
options = ['A', 'B', 'C']
choice_sample = np.random.choice(options, size=5, replace=True)
print("Random choice sample:", choice_sample)

Random integers:
 [[52 93 15 72]
 [61 21 83 87]
 [75 75 88 24]]
Normal samples: [-0.4826188   0.16416482  0.23309524  0.11799461  1.46237812]
Random choice sample: ['A' 'A' 'A' 'C' 'C']
